### ISSUE TITLE
async hooks deprecated :(

### ISSUE THREAD

**Issue by contra** [naugtur/blocked-at#12]
https://github.com/nodejs/node/pull/16972

node 10 will remove it entirely, so this library will cease to work. doubt they will change their mind at this point.

**Comment by naugtur** [comment]
It's just getting rid of old API, async hooks as a feature seem to be staying https://github.com/nodejs/diagnostics/issues/124

**Comment by webtaculars** [comment]
Getting error due to deprecation of async-hooks. Anyone fixed this?

**Comment by naugtur** [comment]
@webtaculars you didn't get them from this.
blocked-at uses the part of async_hook that is not getting deprecated.

All tests pass in node 10 too.
