### ISSUE TITLE
Doesn't report garbage collector

### ISSUE THREAD

**Issue by logidelic** [naugtur/blocked-at#26]
It seems that blocked-at won't report blocking due to garbage collection. For example, I have the following in my code:

```
var beg = Date.now();
global.gc();
console.log(Date.now()-beg)
```

Which in my (crazy) case reports 200ms, but blocked-at seems silent about... Could I be misunderstanding something or is this a real deficiency?

**Comment by naugtur** [comment]
It depends on the function wrapping your code. blocked-at uses async hooks and some of the ways your code can run are not tracked by async hooks (yet, opefully)
eg. bluebird promises only recently started being visible to hooks. 

If you use native promises and put this code in a then function, it should work. No guarantees though :)

Feel free to reopen

**Comment by logidelic** [comment]
Two notes:

- I am using native promises.
- This is in an Electron (5) app. Perhaps that's relevant.

Thanks regardless for the cool library.
