### ISSUE TITLE
Hangs application after first block

### ISSUE THREAD

**Issue by aequasi** [naugtur/blocked-at#6]
Not sure what sort of information you would like, but right after it catches the first block, the application seems to hang

**Comment by naugtur** [comment]
I'd need details on how to reproduce. It didn't happen to me or anyone yet. 
Not saying it's impossible though.

It might be because handling the information it catches or calling your callback also goes above the threshold. 
As means to debug, increasing threshold might be helpful

**Comment by aequasi** [comment]
I think something i was doing was causing an infinite block.... Sorry
